### ISSUE TITLE
moleculer-db-adapter-sequelize SqlAdapter constructor with sequilize instance

### ISSUE THREAD

**Issue by russ666** [moleculerjs/moleculer-db#112]
it would be a good feature, if SqlAdapter constructor could receive sequelize instance as parameter

**Comment by icebob** [comment]
Could you create a PR?

**Comment by icebob** [comment]
Released.

**Comment by luckyguido** [comment]
Hi, regarding this feature I'm having some trouble using it.
If I pass a working sequelize instance to the SqlAdapter() I get this exception:
```
ERROR : Connection error! DatabaseError [SequelizeDatabaseError]: Illegal invocation
    at Query.formatError (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
    at process.callbackTrampoline (internal/async_hooks.js:131:14) {
  parent: TypeError: Illegal invocation
      at handleWriteReq (internal/stream_base_commons.js:53:26)
      at writeGeneric (internal/stream_base_commons.js:145:15)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at Connection._send (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\connection.js:147:24)
      at Connection.query (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\connection.js:151:10)
      at Query.submit (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\query.js:157:18)
      at Client._pulseQueryQueue (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\client.js:481:45)
      at Client.query (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\client.js:576:10)
      at query (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\dialects\postgres\query.js:60:53)
      at Promise._execute (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\debuggability.js:384:9)
      at Promise._resolveFromExecutor (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:518:18)
      at new Promise (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:103:10)
      at Query.run (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\dialects\postgres\query.js:60:9)
      at c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\sequelize.js:655:29
      at tryCatcher (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:131:14) {
    sql: 'SELECT 1+1 AS result',
    parameters: undefined
  },
  original: TypeError: Illegal invocation
      at handleWriteReq (internal/stream_base_commons.js:53:26)
      at writeGeneric (internal/stream_base_commons.js:145:15)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at Connection._send (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\connection.js:147:24)
      at Connection.query (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\connection.js:151:10)
      at Query.submit (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\query.js:157:18)
      at Client._pulseQueryQueue (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\client.js:481:45)
      at Client.query (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\pg\lib\client.js:576:10)
      at query (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\dialects\postgres\query.js:60:53)
      at Promise._execute (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\debuggability.js:384:9)
      at Promise._resolveFromExecutor (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:518:18)
      at new Promise (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:103:10)
      at Query.run (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\dialects\postgres\query.js:60:9)
      at c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\sequelize\lib\sequelize.js:655:29
      at tryCatcher (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\bguido\source\repos\tl-cloud-platform-next\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:131:14) {
    sql: 'SELECT 1+1 AS result',
    parameters: undefined
  },
  sql: 'SELECT 1+1 AS result',
  parameters: undefined
}
```

It seems that sequelize authenticate method has some problem when called inside the constructor, but if I call the authenticate method outside the constructor everything works fine.
This sequelize instance is working and can correctly query the DB.

Any idea??

Thank you very much
Guido
