### ISSUE TITLE
[SequelizeDatabaseError]: invalid input syntax for integer: "[object Object]"

### ISSUE THREAD

**Issue by deman4ik** [moleculerjs/moleculer-db#131]
I have DB service with Sequelize.

I run **find** query from another service like this

```js
import { Op } from "sequelize";
...
this.broker.call(`DB.find`, {
        query: {
          available: { [Op.gte]: 20 }
        }
      })
```

When I start 2 services in one node process it works fine.
But when I use transporter (tried TCP and Redis transporters) I get this error:

```js
Error [SequelizeDatabaseError]: invalid input syntax for integer: "[object Object]"
    at Query.formatError (/home/deman/cpz_platform/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /home/deman/cpz_platform/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
    at Query.run (/home/deman/cpz_platform/node_modules/sequelize/lib/dialects/postgres/query.js:64:23)
    at /home/deman/cpz_platform/node_modules/sequelize/lib/sequelize.js:645:29
    at /home/deman/cpz_platform/node_modules/sequelize/lib/sequelize.js:645:12
    at /home/deman/cpz_platform/node_modules/sequelize/lib/sequelize.js:641:10
    at /home/deman/cpz_platform/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/home/deman/cpz_platform/node_modules/retry-as-promised/index.js:60:10)
    at /home/deman/cpz_platform/node_modules/sequelize/lib/sequelize.js:631:30
    at Sequelize.query (/home/deman/cpz_platform/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.select (/home/deman/cpz_platform/node_modules/sequelize/lib/query-interface.js:1118:27)
    at /home/deman/cpz_platform/node_modules/sequelize/lib/model.js:1756:34
    at processImmediate (internal/timers.js:439:21)
    at Function.findAll (/home/deman/cpz_platform/node_modules/sequelize/lib/model.js:1754:8)
    at SequelizeDbAdapter.createCursor (/home/deman/cpz_platform/node_modules/moleculer-db-adapter-sequelize/src/index.js:328:23)
    at SequelizeDbAdapter.find (/home/deman/cpz_platform/node_modules/moleculer-db-adapter-sequelize/src/index.js:112:15)
    at RobotsService._find (/home/deman/cpz_platform/node_modules/moleculer-db/src/index.js:689:24)
    at RobotsService.handler (/home/deman/cpz_platform/node_modules/moleculer-db/src/index.js:110:17)
    at validateContextParams (/home/deman/cpz_platform/node_modules/moleculer/src/validator.js:48:14)
    at ServiceBroker.timeoutMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/timeout.js:35:14)
    at ServiceBroker.retryMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/retry.js:23:12)
    at ServiceBroker.fallbackMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/fallback.js:18:11)
    at ServiceBroker.errorHandlerMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
    at Transit.requestHandler (/home/deman/cpz_platform/node_modules/moleculer/src/transit.js:432:30)
    at Transit.messageHandler (/home/deman/cpz_platform/node_modules/moleculer/src/transit.js:309:17)
    at TcpTransporter.wrappedMessageHandler [as messageHandler] (/home/deman/cpz_platform/node_modules/moleculer/src/transit.js:67:55)
    at TcpTransporter.incomingMessage (/home/deman/cpz_platform/node_modules/moleculer/src/transporters/base.js:118:16)
    at TcpTransporter.receive (/home/deman/cpz_platform/node_modules/moleculer/src/transporters/tcp.js:277:25)
    at TcpTransporter.onIncomingMessage (/home/deman/cpz_platform/node_modules/moleculer/src/transporters/tcp.js:262:15)
    at Parser.<anonymous> (/home/deman/cpz_platform/node_modules/moleculer/src/transporters/tcp/tcp-reader.js:100:21)
    at Parser.emit (events.js:209:13)
    at Parser._write (/home/deman/cpz_platform/node_modules/moleculer/src/transporters/tcp/parser.js:65:10)
    at doWrite (_stream_writable.js:428:12)
    at writeOrBuffer (_stream_writable.js:412:5)
    at Parser.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:722:22)
From previous event:
    at Transit.request (/home/deman/cpz_platform/node_modules/moleculer/src/transit.js:701:10)
    at ServiceBroker.timeoutMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/timeout.js:35:14)
    at ServiceBroker.retryMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/retry.js:23:12)
    at ServiceBroker.fallbackMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/fallback.js:18:11)
    at ServiceBroker.errorHandlerMiddleware (/home/deman/cpz_platform/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
    at ServiceBroker.call (/home/deman/cpz_platform/node_modules/moleculer/src/service-broker.js:1053:31)
    at BotService.signalsSelectedAsset (/home/deman/cpz_platform/dist/services/telegram/bot.service.js:298:46)
    at /home/deman/cpz_platform/node_modules/telegraf/composer.js:128:56
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'SequelizeDatabaseError',
  code: undefined,
  type: undefined,
  data: undefined,
  retryable: undefined,
  nodeID: 'db'
}
```

And for example query like this 

```js
this.broker.call(`DB.find`, {
        query: {
          available: 20
        }
      })
```

also works fine with transporters.

```
Config:
serializer: "JSON"

Dependencies:
 "moleculer": "^0.14.0-beta4",
 "moleculer-db": "^0.8.2",
 "moleculer-db-adapter-sequelize": "^0.2.2",
 "sequelize": "^5.19.2",

```

**Comment by icebob** [comment]
It seems the Sequelize `Op` is not serializable.

**Comment by deman4ik** [comment]
Thanks @icebob for pointing in right direction.

Found a workaround using  Sequelize [operators aliases](https://sequelize.org/master/manual/querying.html#operators-aliases).

Creating SqlAdapter with operatorsAliases option
```js
new SqlAdapter(
  process.env.PG_DBNAME,
  process.env.PG_USER,
  process.env.PG_PWD,
  {
    dialect: "postgres",
    operatorsAliases: { $gte: Op.gte },
    host: process.env.PG_HOST,
    port: process.env.PG_PORT
 })
```

and then using alias for querying like this

 ```js
 query: {
          available: { $gte: 20 }
        }
```
