### ISSUE TITLE
Error when call mongoose.connect multiple times

### ISSUE THREAD

**Issue by dyabala** [moleculerjs/moleculer-db#221]
#### Issue description

I have two services using moleculer-db-adapter-mongoose, when starting, only one service connect to database successfully but not the other. I have debug with many version of mongoose, the bug occurs with mongoose above "5.10.1". 
Thanks.

#### Version

`moleculer-db-adapter-mongose: "^0.8.6"`
`mongoose: "^5.10.1"`

#### Log

```
[2020-09-15T09:57:59.976Z] INFO  ubuntu/service1: MongoDB adapter has connected successfully.
[2020-09-15T09:57:59.998Z] ERROR ubuntu/service2: Connection error! TypeError: Cannot read property 'connection' of undefined
    at conn.then.result (/home/.../node_modules/moleculer-db-adapter-mongoose/src/index.js:89:15)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by ColinFrick** [comment]
We experience the same problem. Probably caused by this commit: https://github.com/Automattic/mongoose/commit/fadc813eaa32dd357e93beb8614de35e5f346600

Meanwhile we are staying at version 5.10.0

**Comment by dyabala** [comment]
Ok

**Comment by dyabala** [comment]
This issue was fixed by @xuannghia and merged. Many thanks :D .
