### ISSUE TITLE
Problem after upgrade moleculer-db-adapter-mongoose@0.9.0

### ISSUE THREAD

**Issue by thib3113** [moleculerjs/moleculer-db#328]
I got this error : 
```
broker TypeError: conn.then is not a function
    at MongooseDbAdapter.connect (/app/node_modules/moleculer-db-adapter-mongoose/src/index.js:90:15)
    at AnalyzerDBTimeoutService.connect (/app/node_modules/moleculer-db/src/index.js:340:24)
    at connecting (/app/node_modules/moleculer-db/src/index.js:967:11)
    at /app/node_modules/moleculer-db/src/index.js:976:5
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:103:10)
    at AnalyzerDBTimeoutService.started (/app/node_modules/moleculer-db/src/index.js:965:11)
    at AnalyzerDBTimeoutService.<anonymous> (/app/node_modules/moleculer/src/utils.js:212:22)
    at /app/node_modules/moleculer/src/service.js:294:54
    at async Promise.all (index 2)
```

The problem only appear in a docker container, with node 18.12.0 . 

I'm investigating

**Comment by icebob** [comment]
Fix is released.
